name: docs

on:
  push:
    branches: [ master ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up the Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build docs with Maven
        run: mvn javadoc:javadoc

      - name: Copy to Documentation Website Location
        run: |
          rm -rf docs
          cp -rf target/site/apidocs/. docs

      - name: Tidy up the javadocs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: docs
          base-url-path: https://alessiobugetti.github.io/MECVirtualResourceAllocation/

      - name: Log javadoc-cleanup output
        run: |
          echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"

      - name: Commit documentation changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'YOUR NAME HERE'
            git config --global user.email 'YOUR-GITHUB-USERID@users.noreply.github.com'
            git add -A
            git commit -m "Automated API website updates."
          fi

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://alessiobugetti.github.io/MECVirtualResourceAllocation/
          path-to-root: docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          title: "Automated API website updates."
          commit-message: "Automated API documentation website updates."